### ISSUE TITLE
Where is the correct path for the test data?

### ISSUE THREAD

**Issue by jinsanko** [jswoboda/GeoDataPython#8]
I am running "python rangevtimetest.py"
Below is the error message, can you help me to figure where is the right location for test data file
"ran120219.004.hdf5"?   Thank.

Traceback (most recent call last):
  File "rangevtimetest.py", line 26, in <module>
    makeplot('ran120219.004.hdf5')
  File "rangevtimetest.py", line 16, in makeplot
    risr = load_risromti(risrName)[0]
  File "/home/jsk/code/0GeoDataPython/Test/load_isropt.py", line 14, in load_risromti
    risr = GeoData.GeoData(utilityfuncs.readMad_hdf5,(risrName, isrparams))
  File "/home/jsk/code/0GeoDataPython/GeoData/GeoData.py", line 46, in __init__
    (self.data,self.coordnames,self.dataloc,self.sensorloc,self.times) = readmethod(*inputs)
  File "/home/jsk/code/0GeoDataPython/GeoData/utilityfuncs.py", line 59, in readMad_hdf5
    with h5py.File(str(h5fn), "r", libver='latest') as f:
  File "/home/jsk/anaconda/envs/geodata/lib/python3.5/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/jsk/anaconda/envs/geodata/lib/python3.5/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496916508360/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496916508360/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1496916508360/work/h5py/h5f.c:2123)
OSError: Unable to open file (Unable to open file: name = 'ran120219.004.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
(geodata) jsk@ubuntu:~/code/0GeoDataPython/Test$

**Comment by jswoboda** [comment]
You can download the two files you'll need here: https://drive.google.com/file/d/0B37DfeCiFYMgWk9sYmloVGtNOWc/view?usp=sharing
https://drive.google.com/file/d/0B37DfeCiFYMgMFQzSXIza0tJR2M/view?usp=sharing
